version: '2.1'
services:
  # PostgreSQL
  postgres:
    container_name: express-starter-postgres
    build: ./postgres
    environment:
      POSTGRES_USER: 'starter'
      POSTGRES_PASSWORD: 'starter-dev'
      POSTGRES_DB: 'express-starter-db'
    ports:
      - '5544:5432'

  # Backend
  express-starter-api:
    env_file:
      - ./dev.env
    container_name: express-starter-api
    image: node:10
    command: yarn start-server:prod
    working_dir: /app/build
    ports:
      - '8080:8080'
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./:/app
